// API endpoints

// Create User (POST /api/users)
app.post("/api/users", async (req, res) => {
  try {
    const user = new User({ username: req.body.username });
    await user.save();
    res.json({
      username: user.username,
      _id: user.id, // Auto generated by MongoDB
    });
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});
